
services:
   docker-node:
     container_name: ${targetEnv}-node-container
     image: ${targetEnv}-node-image
     restart: always
     depends_on:
      - nginx
     env_file: environment/${targetEnv}.env
     build:
        args:  #these args are available during build time
           - targetEnv=${targetEnv}
        context: ../
        dockerfile: docker/Dockerfile

   nginx:
     container_name: nginx-container
     image: nginx-image
     restart: always
     env_file: environment/${targetEnv}.env
     build:
       context: ../
       dockerfile: nginx/Dockerfile
     ports:
       - 8086:8086

#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-dev
#docker compose -f docker/docker-compose.yml build docker-dev
#docker compose -f docker/docker-compose.yml build docker-prod
#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-prod


# To run all services: docker compose -f docker/docker-compose.yml build