
services:
   docker-node:
     container_name: node-${targetEnv}-container
     restart: always
     depends_on:
      - docker-nginx
     env_file: environment/${targetEnv}.env
     build:
        args:  #these args are available during build time
           - targetEnv=${targetEnv}
        context: ../
        dockerfile: docker/Dockerfile

   docker-nginx:
     container_name: nginx-${targetEnv}-container
     restart: always
     env_file: environment/${targetEnv}.env
     build:
       args:  #these args are available during build time
           - targetEnv=${targetEnv}
       context: ../
       dockerfile: nginx/Dockerfile

#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-dev
#docker compose -f docker/docker-compose.yml build docker-dev
#docker compose -f docker/docker-compose.yml build docker-prod
#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-prod


# To run all services: docker compose -f docker/docker-compose.yml build