
services:
   docker-node:
     container_name: node-${targetEnv}-container
     image: node-${targetEnv}-image
     restart: always
     depends_on:
      - docker-nginx
     env_file: environment/${targetEnv}.env
     build:
        args:  #these args are available during build time
           - targetEnv=${targetEnv}
        context: ../
        dockerfile: docker/Dockerfile

   docker-nginx:
     container_name: nginx-container
     image: nginx-image
     restart: always
     volumes:
       - /etc/letsencrypt/live/mynodeapp-dev.brazilsouth.cloudapp.azure.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem
       - /etc/letsencrypt/live/mynodeapp-dev.brazilsouth.cloudapp.azure.com/privkey.pem:/etc/nginx/ssl/privkey.pem
       - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/ssl/options-ssl-nginx.conf
       - /etc/letsencrypt/ssl-dhparams.pem:/atc/nginx/ssl/ssl-dhparams.pem
     env_file: environment/${targetEnv}.env
     build:
       context: ../
       dockerfile: nginx/Dockerfile
     ports:
       - 80:80

#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-dev
#docker compose -f docker/docker-compose.yml build docker-dev
#docker compose -f docker/docker-compose.yml build docker-prod
#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-prod


# To run all services: docker compose -f docker/docker-compose.yml build